version: '3'

services: 
  bakcend:
    image: registry.gitlab.com/swt-project/backend/backend:productive
    container_name: backend
    ports:
      - "8080:8080"
    depends_on: 
      - mariadb
  web:
    image: registry.gitlab.com/swt-project/web/web:latest
    container_name: web
    ports: 
     - "8081:80"
    depends_on: 
     - backend
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports: 
    - "3306:3306"
    environment: 
      MYSQL_DATABASE: healthcare
      MYSQL_USER: developer
      MYSQL_PASSWORD: lw8Z4dPa7W0f0vm99XpX
    restart: always
    volumes:
     - ./docker-mariadb:/docker-entrypoint-initdb.d
    

