<?php
/**
 * CleaningTaskApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Healthcare App
 *
 * Beschreibung der Rest-Schnitstelle der Healthcare API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CleaningTaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CleaningTaskApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for beaconObjectsBeaconObjectIdCleaningtasksGet
     *
     * Erhalte alle cleaningtasks zu diesem beaconObject.
     *
     */
    public function testBeaconObjectsBeaconObjectIdCleaningtasksGet()
    {

    }

    /**
     * Test case for cleaningtasksAppPost
     *
     * Erhalte die ersten 20 offenen tasks.
     *
     */
    public function testCleaningtasksAppPost()
    {

    }

    /**
     * Test case for cleaningtasksAppSizePost
     *
     * Anzahl der Tasks.
     *
     */
    public function testCleaningtasksAppSizePost()
    {

    }

    /**
     * Test case for cleaningtasksGet
     *
     * Erhalte die ersten 20 offenen tasks.
     *
     */
    public function testCleaningtasksGet()
    {

    }

    /**
     * Test case for cleaningtasksPost
     *
     * Erstelle einen neuen Task.
     *
     */
    public function testCleaningtasksPost()
    {

    }

    /**
     * Test case for cleaningtasksPut
     *
     * Eine reihe CleaningTask bearbeiten.
     *
     */
    public function testCleaningtasksPut()
    {

    }

    /**
     * Test case for cleaningtasksSizeGet
     *
     * Anzahl der Tasks.
     *
     */
    public function testCleaningtasksSizeGet()
    {

    }

    /**
     * Test case for cleaningtasksTaskidDelete
     *
     * löschen.
     *
     */
    public function testCleaningtasksTaskidDelete()
    {

    }

    /**
     * Test case for cleaningtasksTaskidGet
     *
     * Erhalte einen einzelnen Task.
     *
     */
    public function testCleaningtasksTaskidGet()
    {

    }

    /**
     * Test case for cleaningtasksTaskidPut
     *
     * Update einen Task.
     *
     */
    public function testCleaningtasksTaskidPut()
    {

    }

    /**
     * Test case for locationsCleaningtasksGet
     *
     * Liefert alle CleaningTask zu einer örtlichen beschreibung.
     *
     */
    public function testLocationsCleaningtasksGet()
    {

    }

}
