<?php
/**
 * MaintainanceTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Healthcare App
 *
 * Beschreibung der Rest-Schnitstelle der Healthcare API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MaintainanceTaskTest Class Doc Comment
 *
 * @category    Class */
// * @description MaintainanceTask
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MaintainanceTaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MaintainanceTask"
     */
    public function testMaintainanceTask()
    {

    }

    /**
     * Test attribute "picture"
     */
    public function testPropertyPicture()
    {

    }

    /**
     * Test attribute "sub_tasks"
     */
    public function testPropertySubTasks()
    {

    }

    /**
     * Test attribute "repeat_task_in_day"
     */
    public function testPropertyRepeatTaskInDay()
    {

    }

}
